=head1 NAME

Protocol::WebSocket::XS::HTTPRequest - represents HTTP request object

=cut

=head1 SYNOPSIS

    use Protocol::WebSocket::XS::HTTPRequest;
    use URI::XS;

    my $request = Protocol::WebSocket::XS::HTTPRequest->new({
        method  => 'POST',
        uri     => "ws://example.com/",
        body    => '...',
        headers => { 'Origin' => 'http://www.crazypanda.ru'},
    });

    my $r2 = $request;  # => isa 'Protocol::WebSocket::XS::HTTPPacket'

    $request->method;   # => 'POST'
    $request->uri;      # => isa 'URI::XS'

    my $request2 = Protocol::WebSocket::XS::HTTPRequest->new;
    $request2->init({
        method  => 'POST',
        uri     => URI::XS->new("ws://example.com/"),
        body    => '...',
        headers => { 'Origin' => 'http://www.crazypanda.ru'},
    });

=head1 DESCRIPTION

Extends base class L<Protocol::WebSocket::XS::HTTPPacket> with HTTP-request
specific details.

=head1 METHODS

=head2 init($params)

Additional params on top of C<Protocol::WebSocket::XS::HTTPPacket::init>

=over 2

=item method (string)

=item uri (string or URI::XS)

=back

=head2 method()

=head2 method($string)

Gets and sets method in HTTP request.

=head2 uri()

=head2 uri($string or URI::XS object)

Gets and sets URI in HTTP request.

=head1 SEE ALSO

L<Protocol::WebSocket::XS>

L<Protocol::WebSocket::XS::ConnectRequest>

L<Protocol::WebSocket::XS::HTTPPacket>

L<Protocol::WebSocket::XS::HTTPResponse>

L<URI::XS>

=head1 AUTHOR

Pronin Oleg <syber@cpan.org>, Crazy Panda LTD

Ivan Baidakou <i.baydakov@dev.crazypanda.ru>, Crazy Panda LTD

=head1 LICENSE

You may distribute this code under the same terms as Perl itself.

=cut
