=head1 NAME

Protocol::WebSocket::XS::MessageIterator - WebSocket message iterator class

=cut

=head1 DESCRIPTION

The class allows developer traverse on parsed websocket messages.

You cannot instantiate an object of the class direcly, it can be accessed
only via L<Protocol::WebSocket::XS::Parser> or
L<Protocol::WebSocket::XS::FrameIterator>.

=head1 METHODS

=head2 next()

Returns next unvisited L<Protocol::WebSocket::XS::Message> parsed from receive buffer;
otherwise (i.e. when end of buffer is reached) returns C<undef>.

=head2 get_frames()

Returns L<Protocol::WebSocket::XS::FrameIterator>, if there is any unread frame left.
Otherwise returns C<undef>.

=head1 SEE ALSO

L<rfc6455|https://tools.ietf.org/html/rfc6455>

L<Protocol::WebSocket::XS>

L<Protocol::WebSocket::XS::FrameIterator>

L<Protocol::WebSocket::XS::Message>

L<Protocol::WebSocket::XS::Parser>

=head1 AUTHOR

Pronin Oleg <syber@cpan.org>, Crazy Panda LTD

Ivan Baidakou <dmol@cpan.org>, Crazy Panda LTD

=head1 LICENSE

You may distribute this code under the same terms as Perl itself.

=cut
